"""P3 event persistence plus bounded P6-P8 execution surfaces."""

CAPABILITY_STATUS = "degraded"
EVENT_PERSISTENCE_CAPABILITY_STATUS = "available"
TASK_EXECUTION_CAPABILITY_STATUS = "available"
RELATION_EXECUTION_CAPABILITY_STATUS = "available"
TRANSDUCTION_EXECUTION_CAPABILITY_STATUS = "available"
GOVERNANCE_EXECUTION_CAPABILITY_STATUS = "available"
FIRST_PHASE = "P3"

__all__ = [
    "CAPABILITY_STATUS",
    "EVENT_PERSISTENCE_CAPABILITY_STATUS",
    "FIRST_PHASE",
    "GOVERNANCE_EXECUTION_CAPABILITY_STATUS",
    "RELATION_EXECUTION_CAPABILITY_STATUS",
    "TASK_EXECUTION_CAPABILITY_STATUS",
    "TRANSDUCTION_EXECUTION_CAPABILITY_STATUS",
]
